import {SITES,MODELS,SERVICES,CANDIDATES,LOANS,siteOf,candidate,quotePlan,monthlyFixed,relocationQuote,acceptingAt} from './business.js';
const money=n=>'¥'+Math.round(n).toLocaleString('zh-CN');
const esc=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const row=(label,value)=>`<div><dt>${label}</dt><dd>${value}</dd></div>`;
const choice=(kind,id,selected,title,detail,extra='')=>`<button class="plan-choice ${selected?'chosen':''}" data-plan-kind="${kind}" data-plan-value="${id}" aria-pressed="${selected}"><span class="choice-mark" aria-hidden="true">${selected?'✓':'○'}</span><span><b>${title}</b><small>${detail}</small>${extra}</span></button>`;
export class FoundingUI{
  constructor(root){this.root=root;this.step=0;this.last='';}
  render(s,enabled,hasLegacy){const v=s.venture,d=v.draft,q=quotePlan(s);let html;
    if(v.stage==='planning'){
      const titles=['先找一个地址','决定第一步做什么','把团队请到这里','留足开始之后的钱','复核这份筹建方案'];
      let body='';
      if(this.step===0)body=SITES.map(p=>choice('site',p.id,d.site===p.id,p.name,`${p.area}㎡ · 月租 ${money(p.rent)} · ${p.district}`,`<em>${p.note}</em>`)).join('');
      if(this.step===1)body=`<p class="plan-tip">本版开放普通诊所；住院医院、口腔等需独立专业体系，暂未开放。</p>`+MODELS.map(p=>choice('model',p.id,d.model===p.id,p.name,p.note)).join('')+(d.model?`<h3>初始服务</h3>`+SERVICES.map(p=>p.id==='consult'?`<p class="fixed-service">✓ 成人基础门诊 · 包含测量评估与转诊准备</p>`:choice('service',p.id,d.services.includes(p.id),p.name,p.note,`<em>配置 ${money(p.cost)}</em>`)).join(''):'');
      if(this.step===2)body='<p class="plan-tip">同岗位候选人的当前服务能力相同；本版尚未建立个人能力与成长差异。</p>'+['doctor1','nurse','reception',...(d.services.includes('pharmacy')?['pharmacist']:[])].map(slot=>`<h3>${{doctor1:'医学负责人',nurse:'护理',reception:'接待与病案',pharmacist:'药房'}[slot]}</h3>`+CANDIDATES.filter(p=>p.slot===slot).map(p=>choice('staff',p.id,d.staff[slot]===p.id,p.name+' · '+p.role,`${p.scope} · 月薪 ${money(p.monthly)}`,`<em>${p.note}</em>`)).join('')).join('');
      if(this.step===3)body=`<dl class="plan-ledger">${row('目前自有资金',money(s.cash))}${row('一次性筹建投入',money(q.upfront))}${row('每月固定支出估计',money(q.monthly))}</dl><h3>资金方案</h3>`+LOANS.map(l=>choice('loan',l.id,d.loan===l.id,l.name,l.amount?`模拟年利率 ${l.aprBps/100}% · 12期等额本金 · 每30天还款`:'不开立借款，按现有资金筹建。')).join('')+`<p class="plan-tip">贷款为虚构合同，不代表现实报价。${q.payment?'首期预计还款 '+money(q.payment)+'；以后随本金减少。':''}借入资金不是营业收入。</p>`;
      if(this.step===4)body=`<div class="plan-summary"><b>${siteOf(d.site)?.name||'场地未选'} · ${MODELS.find(x=>x.id===d.model)?.name||'定位未选'}</b><p>${d.services.map(x=>SERVICES.find(y=>y.id===x).name).join(' / ')||'服务未选'}</p><p>${Object.values(d.staff).map(id=>candidate(id)?.name).join('、')||'团队未选'}</p></div><dl class="plan-ledger">${q.rows.map(([a,b])=>row(a,money(b))).join('')}${row('借款到账',money(q.loan.amount))}${row('签约后余额',money(q.after))}${row('无收入时资金可覆盖',q.runway.toFixed(1)+' 个月')}</dl><p class="plan-tip">资金覆盖仅按固定支出及首期还款估算；不含后续药耗与额外检查成本，也不保证盈利。未签约的选项可以返回修改。</p>${q.issues.length?`<ul class="plan-issues">${q.issues.map(x=>`<li>${x}</li>`).join('')}</ul>`:`<p class="plan-ready">本版开业条件有对应配置。签约后准备约 ${siteOf(d.site).prepare/60000} 分钟，再由你决定开业。</p>`}`;
      html=`<div class="plan-heading"><span>梅奥 / 筹建手册</span><span>${this.step+1} / 5</span></div><h2>${titles[this.step]}</h2><nav class="plan-steps" aria-label="筹建步骤">${['选址','定位','团队','资金','复核'].map((x,i)=>`<button data-plan-step="${i}" aria-current="${this.step===i?'step':'false'}">${x}</button>`).join('')}</nav><div class="plan-scroll">${body}</div><div class="plan-bottom"><span>签约后 ${money(q.after)}${q.payment?'<small>含借款；需按期归还</small>':''}</span>${this.step<4?`<button data-plan-step="${this.step+1}" class="plan-primary">${['继续选方向','继续选团队','查看资金','复核方案'][this.step]}</button>`:`<button class="plan-primary" data-venture-action="sign" ${q.issues.length?'disabled':''}>签约并开始筹建</button>`}</div><p class="plan-foot">选择暂不扣款。${hasLegacy?'<a href="/?slot=legacy">继续原诊所 ↗</a>':''}</p>`;
    }else{
      const remaining=Math.max(0,Math.ceil((v.readyAt-s.time)/60000)),ready=v.stage==='ready';
      html=`<div class="plan-heading"><span>${siteOf(v.site).name}</span><span>${ready?'准备就绪':'筹建中'}</span></div><h2>${ready?'第一家诊所，准备好了':'房间与团队正在准备'}</h2><p class="plan-tip">${esc(v.message)}</p><dl class="plan-ledger">${row('医疗服务',v.plan.services.map(x=>SERVICES.find(y=>y.id===x).name).join('、'))}${row('医学负责人',candidate(v.plan.staff.doctor1).name)}${row('营业时间','工作日 09:00—17:00')}${row('固定支出估计',money(monthlyFixed(s))+'/月')}${!ready?row('预计剩余',remaining+' 分钟'):''}</dl><button class="plan-primary wide" data-venture-action="open" ${!ready?'disabled':''}>${ready?'决定开业':'团队准备中 · 离线照常推进'}</button><p class="plan-foot">本版筹备时长是演示参数，不代表真实装修或行政办理时间。${hasLegacy?'<a href="/?slot=legacy">查看原诊所 ↗</a>':''}</p>`;
    }
    if(!enabled)html=`<p class="plan-observer">观察模式 · 请在主页面操作筹建</p>`+html;
    if(html!==this.last){const area=this.root.querySelector('.plan-scroll'),scroll=area?.scrollTop||0;this.root.innerHTML=html;this.root.querySelectorAll('[data-plan-kind],[data-venture-action]').forEach(b=>{if(!enabled)b.disabled=true;});const next=this.root.querySelector('.plan-scroll');if(next)next.scrollTop=scroll;this.last=html;}
  }
  go(step){this.step=Math.max(0,Math.min(4,Number(step)));this.last='';this.root.querySelector('.plan-scroll')?.scrollTo(0,0);}
}
export function businessPanel(s,enabled,hasLegacy=false){const v=s.venture,site=siteOf(v.site),loan=v.loan;
  const timing=v.stage==='moving'?'迁址交接中':acceptingAt(s)?'营业中':'非接诊时段';
  return `<p class="subtle">${site.name} · ${site.area}㎡ · ${timing}</p><p class="quote">${esc(v.message)}</p><dl class="ledger">${row('机构定位',MODELS.find(x=>x.id===v.plan.model).name)}${row('固定支出估计',money(monthlyFixed(s))+'/月')}${row('现金',money(s.cash))}${row('未还本金',money(loan?.principal||0))}${row('到期欠付',money(v.arrears))}${row('营业时间','工作日 09:00—17:00')}</dl><details><summary>本次筹建与借款账本</summary>${v.ledger.slice(0,18).map(e=>`<p class="small-note">${esc(e.label)}　${e.amount<0?'−':'+'}${money(Math.abs(e.amount))}</p>`).join('')}</details><h3>管理授权</h3><div class="policy"><span>允许团队按积压情况追加诊室或采样单元</span><button class="switch" role="switch" aria-label="允许团队追加能力" aria-checked="${s.authority}" data-action="authority" ${!enabled?'disabled':''}></button></div><p class="small-note">仍受场地、服务及3万元现金储备约束；日常接诊和补货不需要逐项批准。</p><h3>继续配置能力</h3><p class="small-note">场地有 ${site.rooms} 个功能单元。新增岗位按月计固定成本；患者需求不会因扩建增加。</p>${['chronic','sampling'].filter(id=>!v.plan.services.includes(id)&&(id!=='sampling'||v.plan.services.includes('chronic'))).map(id=>{const service=SERVICES.find(x=>x.id===id);return `<button class="action" data-venture-action="service" data-value="${id}" ${!enabled?'disabled':''}>配置${service.name} · ${money(service.cost)}</button>`}).join('')}${!s.secondRoom&&!s.project?`<button class="action" data-action="expand" ${!enabled?'disabled':''}>第二诊室 · 投入 ¥6,800 / 月增 ¥16,000</button>`:''}${!s.medical.pharmacy.enabled&&!s.medical.pharmacy.project?(!v.plan.staff.pharmacist?`<button class="action" data-venture-action="hire" data-value="lu" ${!enabled?'disabled':''}>聘任药师 · 到岗 ¥2,000 / 月薪 ¥9,500</button>`:`<button class="action" data-action="openPharmacy" ${!enabled?'disabled':''}>筹备院内药房 · ¥9,500</button>`):''}${v.plan.services.includes('sampling')&&!s.medical.annex&&!s.medical.annexProject?`<button class="action" data-action="buildAnnex" ${!enabled?'disabled':''}>独立采样单元 · 投入 ¥24,000 / 月增 ¥8,500</button>`:''}${s.project||s.medical.pharmacy.project||s.medical.annexProject?'<p class="small-note">已委托的配置正在准备，完成后自动投入使用。</p>':''}<h3>空间不够时</h3>${v.relocation?`<p class="subtle">正在迁往 ${siteOf(v.relocation.site).name}，预计还需 ${Math.ceil((v.relocation.due-s.time)/3600000)} 小时；现有患者完成后交接。</p>`:SITES.filter(x=>x.rooms>site.rooms).map(x=>{const q=relocationQuote(s,x.id);return `<details><summary>${x.name} · ${x.area}㎡</summary><p class="small-note">${x.note}<br>迁址投入 ${money(q.cost)}，保留3万元储备；原押金 ${money(q.refund)} 完成交接后退回。暂停新接诊约24小时；报告保留，复诊顺延。新月租 ${money(x.rent)}。以上时长与费用为模拟参数。</p><button class="action" data-venture-action="move" data-value="${x.id}" ${!enabled||s.cash<q.cost+30000?'disabled':''}>决定迁入 ${x.name}</button></details>`}).join('')||'<p class="small-note">目前已使用最大候选场地，更多院区待后续开放。</p>'}<p class="small-note">借款本息、租金和工资按同一现实时间推进。当前尚未模拟税务、医保、完整破产与债务重组。</p>${hasLegacy?'<a class="archive-link" href="/?slot=legacy">原诊所档案 ↗</a>':''}`;
}
